### ISSUE TITLE
Hero + Nav Design proposal

### ISSUE THREAD

**Issue by matthewcpaul** [mclydep/afterhours-show#25]
I will be submitting a pull request with a few design proposals:
- hero section with a background-image (extremely "muted") and the sticky nav
- spot illustrations for the first 2 sections, moving the food bank logo out of section 02, creating an inline link for the sponsor instead

**Comment by matthewcpaul** [comment]
We could have an image of the venue or something as the background—it's pretty hard to see, but I used an image from Artcrank as a placeholder.

The logo on top of a photo of the venue (treated like this) might give it some interesting depth.

<img width="1552" alt="screen shot 2015-09-05 at 6 10 28 pm" src="https://cloud.githubusercontent.com/assets/8001871/9701669/73c2af72-53f9-11e5-9a2b-8b84b70bf8f9.png">

**Comment by patrickchew** [comment]
@mclydep  I kind of like the muted image...hard to know though. What would it look like with the logo over top?

**Comment by matthewcpaul** [comment]
Team, this decision was determined in the meeting today (9/8/15).

We are going to nix the photo idea and illustrate the "bones" of the sign with the logo.
