### ISSUE TITLE
Fix nav breakage on mobile.

### ISSUE THREAD

**Issue by Austinauth** [mclydep/afterhours-show#29]
Navigation breaks on mobile devices. 

Judges & Submit button go away.

![screen shot 2015-09-07 at 9 15 17 pm](https://cloud.githubusercontent.com/assets/6994218/9725019/88417f70-55a5-11e5-8bdd-725132036a16.png)

**Comment by matthewcpaul** [comment]
Yup, let's try to fix this with a % on the nav padding. This may help spread them out at the awkward phablet size as well.

**Comment by matthewcpaul** [comment]
done
