### ISSUE TITLE
Updated Design V4

### ISSUE THREAD

**Issue by patrickchew** [mclydep/afterhours-show#3]
Hey, here's the latest version with the social media accounts and nav. 

This one has updated content under the social media and a new type treatment. "TWITTER" is in Monterrat 10 pt. The judges will have a hover state where a badge comes up and their image goes down to 30% opacity. 
![image](https://cloud.githubusercontent.com/assets/12038342/9593105/2342c3d0-5010-11e5-9366-102da707be9f.png)

Updated Nav on scroll. This can be modified if we think of something better...
![image](https://cloud.githubusercontent.com/assets/12038342/9593111/2d90bcfc-5010-11e5-8694-147dfd9c4600.png)

**Comment by cameronsandage** [comment]
We need to add The Central Texas Food Bank logo in section 02. AND / OR in the Out Partners sections.

**Comment by cameronsandage** [comment]
#### Judges Link

Armin Vit
https://twitter.com/ArminVit
https://twitter.com/ucllc
https://instagram.com/arminvit

Brad Woodard
Website: http://bravethewoods.com/
Twitter: https://twitter.com/brave_the_woods
Dribbble: https://dribbble.com/bradwwoodard

Lauren Dickens
https://twitter.com/laurenydickens
https://instagram.com/el_dick/

Geoff Peveto
https://twitter.com/thedrdc
https://instagram.com/thedecoderring/

---

#### Call for Entry

Submit button :: info@afterhoursatx.com

> > I know it's possible to set an Subject + Body but I can't figure out the string of code for body just the subject. 

Subject - Artist Submission
Body - First Name, Last Name, Phone, Email, URL, Twitter - Please attach up to 3 pieces or provide links to the specific pieces you'd like to use to be considered to be included in Afterhours. (formatted below)

First Name:
Last Name:
Phone: 
Email: 
URL:
Twitter:

Please attach up to 3 pieces or provide links to the specific pieces you'd like to use to be considered to be included in Afterhours. 

---

#### Partners

http://www.lewiscarnegie.com/
http://mathys-potestio.com/

---

#### Social

Facebook: https://www.facebook.com/events/397494623783967/
Twitter : https://twitter.com/AfterhoursATX
Hashtag: #afterhoursatx

**Comment by Austinauth** [comment]
@cameronsandage Thanks for posting these.

**Comment by matthewcpaul** [comment]
I updated Brad's links in the above comment. I also have his headshot here: https://drive.google.com/file/d/0B4FBKJKMZmJ7Q0pQUk5OTGhIeGs/view?usp=sharing

@patrickchew, can you do the photo treatment/croping?

**Comment by cameronsandage** [comment]
From Lauren : Here's my info: 
Twitter: @el__dick
Instagram: el_dick
Dribbble: https://dribbble.com/laurendickens
Website: laurendickens.cool
Favorite Comfort food: You can't beat a good piece of fried chicken.

**Comment by cameronsandage** [comment]
![unnamed-1](https://cloud.githubusercontent.com/assets/10966222/9617504/ca2fb83a-50c7-11e5-8d97-a51ebe60fb87.jpg)
![unnamed](https://cloud.githubusercontent.com/assets/10966222/9617505/ca43d9a0-50c7-11e5-8c3a-1b227769a391.jpg)

**Comment by cameronsandage** [comment]
^^ They don't have a vector version but I asked for a new file.

**Comment by patrickchew** [comment]
The judges headshots (in pink, sans Lauren) can be found here: https://ibm.box.com/s/pkjfu8wxkl6a7r4cuqp15opvsch8cd8b

**Comment by matthewcpaul** [comment]
@patrickchew Armin's photo stands out from the others b/c of the all-white background. In the mockup, there was still a light-pink background showing... Up to you, but I thought it was better if you could see the background/outline of the crop.

**Comment by patrickchew** [comment]
I added the icons to the box folder, minus 1. I'll upload that later this weekend. 
https://ibm.box.com/s/pkjfu8wxkl6a7r4cuqp15opvsch8cd8b

**Comment by patrickchew** [comment]
I added the 4th badge, so the file now has them for each judge: 
https://ibm.box.com/s/pkjfu8wxkl6a7r4cuqp15opvsch8cd8b

**Comment by matthewcpaul** [comment]
closing this issue for now
