### ISSUE TITLE
Flexbox rows (judges & sponsors) breaking in firefox.

### ISSUE THREAD

**Issue by Austinauth** [mclydep/afterhours-show#31]
Update the flexbox styles to use the appropriate vendor prefixes (hopefully this solves the issue).

![screen shot 2015-09-07 at 9 18 37 pm](https://cloud.githubusercontent.com/assets/6994218/9725050/01ad1234-55a6-11e5-84d7-eb21952783c0.png)

**Comment by matthewcpaul** [comment]
wtf :joy: Yea this is probably the issue you mentioned earlier today. I had to fix something like this for iOS browsers this weekend too.

**Comment by Austinauth** [comment]
@matthewcpaul Fixed in Firefox, still an issue in Safari.

**Comment by matthewcpaul** [comment]
word, there's a separate issue, so I will close this
