### ISSUE TITLE
Coding typographic grid + styles

### ISSUE THREAD

**Issue by matthewcpaul** [mclydep/afterhours-show#4]
Setting up the Scss directory and coding the grid + typography

**Comment by matthewcpaul** [comment]
The `grid-and-type` branch is in-progress and not ready for a pull request. @Austinauth, let me know if you're going to pick this up before tonight, and we can merge this in.

**Comment by Austinauth** [comment]
@mclydep Haven't touched anything else, should be no merge conflicts.

**Comment by matthewcpaul** [comment]
Closing due to the Scss overhaul
