### ISSUE TITLE
Flexbox rows (sponsors) are jank on safari

### ISSUE THREAD

**Issue by matthewcpaul** [mclydep/afterhours-show#47]
and probably iOS browsers... I think it's the same syntax issue I had to fix with the judges section this past weekend.

<img width="1440" alt="screen shot 2015-09-08 at 6 38 07 pm" src="https://cloud.githubusercontent.com/assets/8001871/9750091/f35386a6-5658-11e5-85a6-b743cc78c518.png">

**Comment by Austinauth** [comment]
@matthewcpaul Still a problem. I fixed this in Firefox, but I have no idea what is happening in Safari.

**Comment by matthewcpaul** [comment]
done
