### ISSUE TITLE
Properly center the secondary mark

### ISSUE THREAD

**Issue by matthewcpaul** [mclydep/afterhours-show#48]
It isn't quite sitting in the center b/c it is relatively positioned. This is the best way I know how:

<img width="215" alt="screen shot 2015-09-08 at 7 07 52 pm" src="https://cloud.githubusercontent.com/assets/8001871/9750408/05023e7a-565d-11e5-9bc8-9ce11d77cc1d.png">

**Comment by Austinauth** [comment]
@matthewcpaul It should be centered because the parent has `text-align: center;`. I could be wrong though.

**Comment by matthewcpaul** [comment]
Hm, It was a little off for some reason. I measured, and compared to the judges photos. The fix above should do the trick. I can add it in tonight.

**Comment by matthewcpaul** [comment]
done
